sudo: false
language: node_js
node_js:
  - '8'
  - '10'
services:
  - mongodb
before_install:
  - npm i npminstall -g
install:
  - npminstall
script:
  - MONGODB_URL=mongodb://localhost:27017/test npm run ci
after_script:
  - npminstall codecov && codecov
